name: http_extensions_protobuf
description: >-
  An http extension that serializes requests body to protobuf and deserializes
  responses' content from protobuf.
  Uses Cancelable Token HTTP Client library which allows canceling requests.
  (fully compatible with HTTP Client library)
version: 1.1.0
homepage: https://github.com/anycode/http_extensions

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  cancellation_token_http: ^1.2.0
  meta: ^1.9.0
  http_extensions: #^1.1.0
    #path: ../http_extensions
    git:
      url: https://github.com/anycode/http_extensions.git
      path: http_extensions
      ref: cancelable
  logging: ^1.1.1
  protobuf: ^2.1.0

