name: http_extensions_headers
description: >-
  An http extension that adds headers to requests.
  Uses Cancelable Token HTTP Client library which allows canceling requests.
  (fully compatible with HTTP Client library)
version: 1.1.2
homepage: https://github.com/anycode/http_extensions
publish_to: https://pub.anycode.dev

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  cancellation_token_http: ^2.0.0
  meta: ^1.12.0
  http_extensions:
    hosted: https://pub.anycode.dev
    version: ^1.1.2
  logging: ^1.2.0
dev_dependencies:
  lints: ^3.0.0
