name: http_extensions
description: >-
  Base classes for building extensions for http package.
  Uses Cancelable Token HTTP Client library which allows canceling requests.
  (fully compatible with HTTP Client library)
version: 1.1.2
homepage: https://github.com/anycode/http_extensions
publish_to: https://pub.anycode.dev

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  cancellation_token_http: ^2.0.0
  meta: ^1.11.0
dev_dependencies:
  lints: ^3.0.0
