name: http_extensions
description: >-
  Base classes for building extensions for http package.
  Uses Cancelable Token HTTP Client library which allows canceling requests.
  (fully compatible with HTTP Client library)
version: 1.1.1
homepage: https://github.com/anycode/http_extensions

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  cancellation_token_http: ^1.2.0
  meta: ^1.9.1
