name: http_extensions_retry
description: >-
  An http extension that retries failed requests.
  Uses Cancelable Token HTTP Client library which allows canceling requests.
  (fully compatible with HTTP Client library)
version: 1.1.2
homepage: https://github.com/anycode/http_extensions
publish_to: 'none'

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  cancellation_token_http: ^2.0.0
  meta: ^1.11.0
  http_extensions: #^1.1.1
    #path: ../http_extensions
    git:
      url: https://github.com/anycode/http_extensions.git
      path: http_extensions
      ref: cancelable
  logging: ^1.2.0
dev_dependencies:
  lints: ^3.0.0
